project: 
  type: book

book: 
  page-navigation: true
  title: "Pilot data: deep-set longline temperature-depth recorders" 
  author:
    - name: Phoebe Woodworth-Jefcoats
      affiliations:
        - name: NOAA Fisheries
          department: Pacific Islands Fisheries Science Center
    - name: Revere Wood
      affiliations:
        - name: NOAA Fisheries
          department: Pacific Islands Fisheries Science Center
  chapters:
    - index.qmd
    - ExecutiveSummary.qmd
    - MainBodyText.qmd
    - References.qmd
    
bibliography: references.bib
csl: apa.csl

format:
  docx:
    toc: true
    toc-depth: 4
    reference-doc: OFFICIAL_PIFSC_Data_Reports_Apr_2025.docx
    always_allow_html: true
